# Teaclave Build Config

# Intel Attestation Service root CA certificate to verify attestation report
as_root_ca_cert = { path = "../keys/ias_root_ca_cert.pem" }
# For DCAP, use the following cert
#as_root_ca_cert = { path = "../keys/dcap_root_ca_cert.pem" }

# Auditors' public keys to verify their endorsement signatures
auditor_public_keys = [
    { path = "../keys/auditors/godzilla/godzilla.public.pem" },
    { path = "../keys/auditors/optimus_prime/optimus_prime.public.pem" },
    { path = "../keys/auditors/albus_dumbledore/albus_dumbledore.public.pem"},
]

# RPC max message size
rpc_max_message_size = 409600
